# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as proto_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/message.proto\x1a\x14proto/response.proto\"@\n\x07Request\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\"\n\x0crequest_type\x18\x02 \x01(\x0e\x32\x0c.RequestType\"\x98\x01\n\x08Response\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12&\n\rnone_response\x18\x03 \x01(\x0b\x32\r.NoneResponseH\x00\x12(\n\x0eimage_response\x18\x04 \x01(\x0b\x32\x0e.ImageResponseH\x00\x42\x12\n\x10\x44\x65tailedResponse*@\n\x0bRequestType\x12\t\n\x05Image\x10\x00\x12\x0e\n\nComponents\x10\x01\x12\x0b\n\x07\x44\x65tails\x10\x02\x12\t\n\x05Video\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUESTTYPE']._serialized_start=266
  _globals['_REQUESTTYPE']._serialized_end=330
  _globals['_REQUEST']._serialized_start=45
  _globals['_REQUEST']._serialized_end=109
  _globals['_RESPONSE']._serialized_start=112
  _globals['_RESPONSE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
